import os

base_dir = r"E:\obsidian\JavaDeveloper\11_实战专题"

# ========== 02 并发编程 (4篇) ==========
concurrency_topics = [
    {
        "filename": "24_任务调度系统设计.md",
        "title": "任务调度系统设计",
        "intro": "任务调度系统核心是：**调度策略 + 执行隔离 + 失败重试 + 分片扩展**。需要支持延迟任务、优先级任务、Cron 任务等场景，是分布式系统的基础中间件。",
        "sections": [
            ("架构设计", "```\n┌─────────────┐   提交   ┌─────────────┐\n│  业务应用  │ ───────→ │  调度中心   │\n└─────────────┘         │ (Scheduler)  │\n                             └──────┬──────┘\n                                    │ 分片下发\n                    ┌───────────────┼───────────────┐\n                    ▼               ▼               ▼\n             ┌────────┐      ┌────────┐      ┌────────┐\n             │ 执行器 │      │ 执行器 │      │ 执行器 │\n             │ (Worker)│      │ (Worker)│      │ (Worker)│\n             └────────┘      └────────┘      └────────┘\n```"),
            ("场景 A：延迟任务实现（5 秒后执行）", "### 方案对比\n| 方案 | 优点 | 缺点 | 适用 |\n|------|------|------|------|\n| DelayQueue | 无锁、JDK 内置 | 单机 | 轻量 |\n| Redis ZSet | 分布式、简单 | 需要轮询 | 中小规模 |\n| 时间轮（Netty HashedWheelTimer）| O(1) 插入、O(1) 触发 | 内存占用 | 百万级任务 |\n| MQ 延迟消息 | 可靠、解耦 | 依赖 MQ | 高可靠 |\n\n### Redis ZSet 实现延迟任务\n```java\n@Service\npublic class DelayTaskService {\n    private static final String KEY = \"delay:tasks\";\n    \n    @Autowired\n    private RedisTemplate<String, String> redis;\n    \n    // 提交延迟任务\n    public void submitTask(String taskId, long delaySeconds) {\n        double executeTime = System.currentTimeMillis() + delaySeconds * 1000;\n        redis.opsForZSet().add(KEY, taskId, executeTime);\n    }\n    \n    // 轮询执行（定时任务，每秒扫一次）\n    @Scheduled(fixedDelay = 1000)\n    public void pollTasks() {\n        double now = System.currentTimeMillis();\n        Set<String> tasks = redis.opsForZSet()\n            .rangeByScore(KEY, 0, now);\n        \n        for (String taskId : tasks) {\n            // 用 ZREM 原子删除（防止多机重复执行）\n            Long removed = redis.opsForZSet().remove(KEY, taskId);\n            if (removed > 0) {  // 只有删除成功的才执行\n                executeTask(taskId);\n            }\n        }\n    }\n}\n```"),
            ("场景 B：分片调度（支持水平扩展）", "### 问题\n```\n单机调度：任务多 → 调度线程池满 → 任务堆积\n解决：分片（Sharding），每个执行器只执行部分任务\n```\n\n### 分片算法\n```java\n// 任务分片：按任务 ID hash 分片\npublic class ShardingScheduler {\n    private final int shardTotal;  // 总分片数（= 执行器数量）\n    private final int shardIndex;   // 当前执行器分片索引\n    \n    public void schedule() {\n        List<Task> allTasks = taskMapper.selectPendingTasks();\n        for (Task task : allTasks) {\n            // 分片：taskId % shardTotal == shardIndex 才执行\n            if (task.getId() % shardTotal == shardIndex) {\n                executeAsync(task);\n            }\n        }\n    }\n    \n    // 动态扩缩容：执行器上线/下线时，重新分配分片\n    @ZookeeperWatch(path = \"/scheduler/workers\")\n    public void onWorkersChange(List<String> workers) {\n        this.shardTotal = workers.size();\n        this.shardIndex = workers.indexOf(myId);\n        // 重新分片，可能触发任务迁移\n    }\n}\n```\n\n### 生产方案：XXL-Job / Elastic-Job\n- **XXL-Job**：轻量，中心化调度，执行器通过心跳注册\n- **Elastic-Job**：去中心化，基于 ZooKeeper 选主，分片更均匀"),
            ("场景 C：失败重试（指数退避）", "```java\n// 重试策略：指数退避 + 最大重试次数\npublic class RetryPolicy {\n    private final int maxRetries = 5;\n    private final long baseDelayMs = 1000;  // 1秒\n    \n    public long getRetryDelay(int retryCount) {\n        if (retryCount >= maxRetries) return -1;  // 放弃\n        // 指数退避：1000, 2000, 4000, 8000, 16000\n        return baseDelayMs * (1L << retryCount);\n    }\n}\n\n// 任务执行框架\npublic class TaskExecutor {\n    private final RetryPolicy retryPolicy = new RetryPolicy();\n    \n    public void executeWithRetry(Task task) {\n        int attempt = 0;\n        while (attempt <= retryPolicy.maxRetries) {\n            try {\n                doExecute(task);\n                task.markSuccess();\n                return;\n            } catch (Exception e) {\n                attempt++;\n                long delay = retryPolicy.getRetryDelay(attempt);\n                if (delay < 0) {\n                    task.markFailed(\"重试次数耗尽\");\n                    return;\n                }\n                // 延迟重试（提交到延迟队列）\n                delayQueue.offer(new DelayedTask(task, delay));\n            }\n        }\n    }\n}\n```"),
        ]
    },
    {
        "filename": "25_高并发库存扣减系统设计.md",
        "title": "高并发库存扣减系统设计",
        "intro": "库存扣减是秒杀/电商核心场景，核心矛盾是：**高并发读 + 精确扣减不超卖 + 高性能**。设计要点：无锁化设计、Redis 预减、数据库兜底、分桶抗热 Key。",
        "sections": [
            ("架构设计", "```\n        用户请求\n           │\n           ▼\n   ┌───────────────────┐\n   │   Redis 预减库存    │  ← 第一道防线（原子操作）\n   │   DECR 或 Lua 脚本  │\n   └─────────┬─────────┘\n             │ 预减成功\n             ▼\n   ┌───────────────────┐\n   │   消息队列          │  ← 异步削峰\n   │   （有序，防止超卖） │\n   └─────────┬─────────┘\n             │\n             ▼\n   ┌───────────────────┐\n   │   DB 最终扣减        │  ← 第二道兜底\n   │   UPDATE ... WHERE  │\n   └───────────────────┘\n```"),
            ("场景 A：Redis 原子扣减（Lua 脚本保证多操作原子性）", "```lua\n-- 库存扣减 Lua 脚本（保证原子性）\n-- KEYS[1]: 库存 key\n-- ARGV[1]: 扣减数量\n-- ARGV[2]: 用户 ID（防重复）\n\nlocal stock = tonumber(redis.call('get', KEYS[1]))\nif not stock or stock < tonumber(ARGV[1]) then\n    return -1  -- 库存不足\nend\n\n-- 防重复（用户已购买过？）\nlocal userKey = 'stock:user:' .. ARGV[2] .. ':' .. KEYS[1]\nif redis.call('exists', userKey) == 1 then\n    return -2  -- 重复购买\nend\n\n-- 扣减库存 + 记录用户\nredis.call('decrby', KEYS[1], ARGV[1])\nredis.call('setex', userKey, 3600, '1')\nreturn 1  -- 成功\n```\n\n```java\n// Java 调用 Lua 脚本\n@Service\npublic class StockService {\n    private final String luaScript = \"...\"  // 上面的 Lua 脚本\n    \n    public boolean deductStock(String productId, int amount, Long userId) {\n        Long result = (Long) redisTemplate.execute(\n            new DefaultRedisScript<>(luaScript, Long.class),\n            Collections.singletonList(\"stock:\" + productId),\n            String.valueOf(amount),\n            String.valueOf(userId)\n        );\n        return result != null && result > 0;\n    }\n}\n```"),
            ("场景 B：分桶抗热 Key", "### 问题\n```\n热门商品（如 iPhone 15）—— 所有请求打同一个 Redis key\nRedis 单线程 → 热点 key 成为瓶颈\n```\n\n### 分桶方案\n```java\n// 库存 10000 → 分成 10 个桶，每桶 1000\npublic class BucketStockService {\n    private final int BUCKET_COUNT = 10;\n    \n    public boolean deduct(Long userId, String productId, int amount) {\n        // 1. 随机选择一个桶尝试\n        int bucketId = ThreadLocalRandom.current().nextInt(BUCKET_COUNT);\n        String bucketKey = \"stock:\" + productId + \":bucket:\" + bucketId;\n        \n        Long remain = redisTemplate.opsForValue().decrement(bucketKey, amount);\n        \n        if (remain >= 0) return true;  // 扣减成功\n        \n        // 2. 当前桶不够，尝试其他桶\n        redisTemplate.opsForValue().increment(bucketKey, amount);  // 回补\n        \n        for (int i = 0; i < BUCKET_COUNT; i++) {\n            String otherBucket = \"stock:\" + productId + \":bucket:\" + i;\n            remain = redisTemplate.opsForValue().decrement(otherBucket, amount);\n            if (remain >= 0) return true;\n            redisTemplate.opsForValue().increment(otherBucket, amount);\n        }\n        \n        return false;  // 所有桶都不够\n    }\n}\n```"),
            ("场景 C：数据库兜底方案", "```sql\n-- 必须加 WHERE stock >= amount，不能先 SELECT 再 UPDATE\nUPDATE product_stock \nSET stock = stock - #{amount},\n    sold = sold + #{amount}\nWHERE product_id = #{productId}\n  AND stock >= #{amount};\n\n-- MyBatis 判断影响行数\nif (affectedRows == 0) {\n    throw new StockNotEnoughException();\n}\n```\n\n### 一致性对账\n```java\n// 定时任务：Redis 库存 vs 数据库实际销量\n@Scheduled(cron = \"0 0 2 * * ?\")  // 每天凌晨 2 点\npublic void reconcileStock() {\n    List<Product> products = productMapper.selectAll();\n    for (Product p : products) {\n        int redisStock = getRedisStock(p.getId());\n        int dbSold = p.getSold();\n        int dbStock = p.getStock();\n        \n        // 预期：redisStock == dbStock\n        // 如果不一致，告警 + 人工介入\n        if (redisStock != dbStock) {\n            alert(\"库存不一致: productId=\" + p.getId());\n        }\n    }\n}\n```"),
        ]
    },
    {
        "filename": "26_线程安全缓存框架设计.md",
        "title": "线程安全缓存框架设计",
        "intro": "设计一个类似 Guava Cache 的线程安全缓存框架，核心是：**ConcurrentHashMap 分段锁 + 淘汰策略（LRU/LFU）+ 容量控制 + 过期清理**。重点理解无锁读操作和并发淘汰的实现。",
        "sections": [
            ("架构设计", "```\n┌──────────────────────────────────────┐\n│           缓存框架                   │\n│  ┌──────────────────────────────┐  │\n│  │    ConcurrentHashMap          │  │\n│  │  (存储缓存条目)                │  │\n│  └───────────┬──────────────────┘  │\n│              │                       │\n│  ┌───────────▼──────────────────┐  │\n│  │    淘汰算法                   │  │\n│  │  (LRU 队列 / LFU 计数)       │  │\n│  └───────────┬──────────────────┘  │\n│              │                       │\n│  ┌───────────▼──────────────────┐  │\n│  │    过期清理线程                │  │\n│  │  (懒清理 + 定时清理)          │  │\n│  └──────────────────────────────┘  │\n└──────────────────────────────────────┘\n```"),
            ("场景 A：ConcurrentHashMap 实现缓存（简化版）", "```java\npublic class SimpleCache<K, V> {\n    private final Map<K, V> cache = new ConcurrentHashMap<>();\n    private final Map<K, Long> expireAt = new ConcurrentHashMap<>();\n    private final int maxSize;\n    \n    public SimpleCache(int maxSize) {\n        this.maxSize = maxSize;\n    }\n    \n    public V get(K key) {\n        Long exp = expireAt.get(key);\n        if (exp != null && exp < System.currentTimeMillis()) {\n            remove(key);  // 懒清理\n            return null;\n        }\n        return cache.get(key);\n    }\n    \n    public void put(K key, V value, long ttlSeconds) {\n        if (cache.size() >= maxSize) {\n            // 简化版淘汰：随机删除一个（生产用 LRU）\n            K randomKey = cache.keySet().iterator().next();\n            remove(randomKey);\n        }\n        cache.put(key, value);\n        expireAt.put(key, System.currentTimeMillis() + ttlSeconds * 1000);\n    }\n    \n    private void remove(K key) {\n        cache.remove(key);\n        expireAt.remove(key);\n    }\n}\n```\n\n**问题**：淘汰策略太简单，没有 LRU/LFU。实际生产用 Guava Cache 或 Caffeine。"),
            ("场景 B：LRU 淘汰算法实现", "```java\n// 线程安全的 LRU 缓存（用 ReadWriteLock）\npublic class LruCache<K, V> {\n    private final int maxSize;\n    private final Map<K, Node<K, V>> map;\n    private final Node<K, V> head, tail;  // 双向链表\n    private final ReadWriteLock lock = new ReentrantReadWriteLock();\n    \n    // 访问时移到队尾（最久未使用在队头）\n    public V get(K key) {\n        lock.readLock().lock();\n        try {\n            Node<K, V> node = map.get(key);\n            if (node != null) {\n                moveToTail(node);  // 移到队尾（最近使用）\n                return node.value;\n            }\n            return null;\n        } finally {\n            lock.readLock().unlock();\n        }\n    }\n    \n    // 插入时检查容量，超过则删除队头\n    public void put(K key, V value) {\n        lock.writeLock().lock();\n        try {\n            Node<K, V> node = map.get(key);\n            if (node != null) {\n                node.value = value;\n                moveToTail(node);\n            } else {\n                node = new Node<>(key, value);\n                map.put(key, node);\n                addToTail(node);\n                \n                if (map.size() > maxSize) {\n                    Node<K, V> removed = removeHead();  // 淘汰最久未使用\n                    map.remove(removed.key);\n                }\n            }\n        } finally {\n            lock.writeLock().unlock();\n        }\n    }\n}\n```\n\n**Caffeine 方案**：用 `ConcurrentHashMap` + W-TinyLFU 算法，无锁读，性能碾压上面的方案。面试直接说「生产用 Caffeine」。"),
            ("场景 C：缓存穿透/击穿防护", "```java\n// 方案1：布隆过滤器（防止缓存穿透）\npublic class BloomFilterCache {\n    private final BloomFilter<String> bloomFilter = \n        BloomFilter.create(Funnels.stringFunnel(), 10_000_000, 0.01);\n    \n    public User getUser(Long id) {\n        // 1. 布隆过滤器快速判断（不存在的一定不存在）\n        if (!bloomFilter.mightContain(\"user:\" + id)) {\n            return null;  // 一定不存在，不查缓存和 DB\n        }\n        \n        // 2. 查缓存\n        User user = cache.get(\"user:\" + id);\n        if (user != null) return user;\n        \n        // 3. 查 DB\n        user = userMapper.selectById(id);\n        if (user != null) {\n            cache.put(\"user:\" + id, user);\n        } else {\n            // 空值缓存（防止穿透，TTL 设短一点）\n            cache.put(\"user:\" + id, null, 60);\n        }\n        return user;\n    }\n}\n```"),
        ]
    },
    {
        "filename": "27_百万级定时任务调度平台设计.md",
        "title": "百万级定时任务调度平台设计",
        "intro": "支持百万级定时任务的调度平台，核心是 **时间轮（Timing Wheel）+ 分片调度 + 持久化 + 集群选举**。Netty 的 HashedWheelTimer 是经典实现，大规模场景需要分层时间轮。",
        "sections": [
            ("架构设计", "```\n┌──────────────────────────────────────┐\n│          调度平台                     │\n│  ┌────────────┐    ┌────────────┐  │\n│  │  任务注册   │    │  集群选举   │  │\n│  │  (Web UI)  │    │  (ZooKeeper)│  │\n│  └─────┬──────┘    └──────┬─────┘  │\n│        │                  │         │\n│        ▼                  ▼         │\n│  ┌──────────────────────────────┐  │\n│  │      时间轮（分级）           │  │\n│  │  Round 1 (秒级)             │  │\n│  │  Round 2 (分钟级)           │  │\n│  │  Round 3 (小时级)           │  │\n│  └──────────┬───────────────────┘  │\n│             │                      │\n│  ┌──────────▼───────────────────┐  │\n│  │  任务分发（分片）             │  │\n│  │  Worker 集群                 │  │\n│  └──────────────────────────────┘  │\n└──────────────────────────────────────┘\n```"),
            ("场景 A：时间轮（HashedWheelTimer）原理", "### Netty HashedWheelTimer\n```\n时间轮类似时钟：\n- 轮盘有 N 个槽（默认 512）\n- 每个槽是一个双向链表，存到期任务\n- 指针每秒跳一格，跳到哪个槽就执行那个槽的任务\n- 层数（round）：任务到期时间 > 一轮时间，需要多轮\n```\n\n```java\n// Netty HashedWheelTimer 使用\nHashedWheelTimer timer = new HashedWheelTimer(\n    new DefaultThreadFactory(\"timer\"),\n    100,                           // tick 间隔（毫秒）\n    TimeUnit.MILLISECONDS,\n    512                            // 槽数\n);\n\ntimer.newTimeout(timeout -> {\n    System.out.println(\"5秒后执行\");\n}, 5, TimeUnit.SECONDS);\n```\n\n### 时间复杂度\n| 操作 | 时间复杂度 |\n|------|------------|\n| 添加任务 | O(1) |\n| 取消任务 | O(1)（从链表中删除）|\n| 触发任务 | O(n)（n = 槽数，但每个槽的任务数很少）|"),
            ("场景 B：分层时间轮（大规模场景）", "### 问题\n```\n单层时间轮：如果要支持「1 小时后执行」→ 轮盘需要很大 → 内存浪费\n解决：分层时间轮（类似时钟的 秒/分/时）\n```\n\n### Kafka 分层时间轮实现\n```\nLevel 1：秒级时间轮（tick=1s, wheelSize=60）→ 覆盖 60 秒\nLevel 2：分钟级时间轮（tick=60s, wheelSize=60）→ 覆盖 1 小时\nLevel 3：小时级时间轮（tick=3600s, wheelSize=24）→ 覆盖 1 天\n\n任务到期时间 > 当前轮覆盖范围 → 升级到上一级时间轮\n任务到期时间 <= 当前轮覆盖范围 → 降级到下一级时间轮\n最终到达 Level 1，到期执行\n```\n\n```java\n// Kafka TimingWheel 核心思想（简化）\npublic class TimingWheel {\n    private final long tickMs;\n    private final int wheelSize;\n    private final long interval;  // tickMs * wheelSize\n    private final ArrayDeque<Task>[] slots;\n    private TimingWheel overflowWheel;  // 上级时间轮\n    \n    public void add(Task task) {\n        if (task.expireMs < currentTime + interval) {\n            // 能放在当前轮 → 放到对应槽\n            int slot = (int)((task.expireMs / tickMs) % wheelSize);\n            slots[slot].add(task);\n        } else {\n            // 放不下 → 放上级时间轮\n            overflowWheel.add(task);\n        }\n    }\n}\n```"),
            ("场景 C：集群调度（防重复执行）", "### 问题\n```\n多台调度器同时工作 → 同一任务被多次触发 → 重复执行\n```\n\n### 解决方案：集群选举 + 分片\n```java\n// 1. ZooKeeper 选主（只有 Leader 触发任务）\npublic class LeaderSelectorListener implements LeaderLatchListener {\n    @Override\n    public void takeLeadership() throws Exception {\n        // 成为 Leader → 开始调度\n        scheduler.start();\n        // 阻塞直到失去领导权\n        Thread.sleep(Long.MAX_VALUE);\n    }\n}\n\n// 2. 分片（多台机器同时工作，但各管各的）\n// 更适合大规模场景：每台机器管一部分任务\npublic class ShardingScheduler {\n    private int shardIndex;  // 当前机器分片\n    private int shardTotal; // 总分片数\n    \n    public void schedule() {\n        List<Task> tasks = taskDao.selectAll();\n        for (Task task : tasks) {\n            // 任务 ID 取模分片\n            if (task.getId() % shardTotal == shardIndex) {\n                execute(task);\n            }\n        }\n    }\n}\n```"),
        ]
    },
]

for topic in concurrency_topics:
    filepath = os.path.join(base_dir, topic["filename"])
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"# {topic['title']}\n\n")
        f.write(f"> {topic['intro']}\n\n---\n\n")
        for title, content in topic["sections"]:
            f.write(f"## {title}\n\n")
            f.write(content.strip() + "\n\n---\n\n")
        f.write("## 排查 Checklist\n\n```\n□ （待补充）\n```\n\n---\n\n")
        f.write("## 涉及知识点\n\n| 概念 | 所属域 | 关键点 |\n|------|--------|--------|\n| （待补充）| （待补充）| （待补充）|\n\n---\n\n")
        f.write("## 我的实战笔记\n\n-（待补充，项目中的真实经历）\n")
    print(f"✅ {topic['filename']}")

print("并发编程 4 篇完成！")
